// <auto-generated />
using System;
using LiveTrackingService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LiveTrackingService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(LiveTrackingDbContext))]
    partial class LiveTrackingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LiveTrackingService.Domain.Entities.LiveTripTracking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("float");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("float");

                    b.Property<double?>("CurrentSpeed")
                        .HasColumnType("float");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrackingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("LiveTripTrackings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            CurrentLatitude = 31.949999999999999,
                            CurrentLongitude = 35.933300000000003,
                            CurrentSpeed = 58.399999999999999,
                            DriverId = new Guid("c3333333-3333-3333-3333-333333333333"),
                            LastUpdatedAt = new DateTime(2026, 6, 30, 21, 14, 40, 670, DateTimeKind.Utc).AddTicks(1353),
                            TrackingStatus = "Active",
                            TripId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            VehicleId = new Guid("d4444444-4444-4444-4444-444444444444")
                        });
                });

            modelBuilder.Entity("LiveTrackingService.Domain.Entities.TrackingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<double?>("Speed")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TrackingHistories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5555555-5555-5555-5555-555555555555"),
                            Latitude = 31.949999999999999,
                            Longitude = 35.933300000000003,
                            Speed = 52.100000000000001,
                            Timestamp = new DateTime(2026, 6, 30, 21, 12, 40, 670, DateTimeKind.Utc).AddTicks(2201),
                            TripId = new Guid("b2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("f6666666-6666-6666-6666-666666666666"),
                            Latitude = 31.9512,
                            Longitude = 35.935000000000002,
                            Speed = 58.399999999999999,
                            Timestamp = new DateTime(2026, 6, 30, 21, 13, 40, 670, DateTimeKind.Utc).AddTicks(2209),
                            TripId = new Guid("b2222222-2222-2222-2222-222222222222")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
